
name: (on push) zip release readme
on:
  push:
    paths:
      - 'images/**'
jobs:
  zip-files:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Zip images
        run: |
          import os
          import subprocess
          subprocess.run(["zip", "-r", "images.zip", "images/"],
            stdout=subprocess.DEVNULL)
        shell: python
      - name: Upload plugins to release
        uses: ncipollo/release-action@v1.11.1
        with:
          name: Downloads
          tag: Latest
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          artifacts: "*.zip"
      - name: del Zip
        run: |
          import os
          os.remove('images.zip')
          aifolder = os.listdir('images/')
          for ai in aifolder:
            sub1 = os.listdir('images/' + ai + '/')
            for each in sub1:
              if each.isfile():
                with open('images.md', 'w') as output:
                  output.writelines(each + '\n')
        shell: python
      - name: Commit file
        run: |
          git config user.name "zuckung" 
          git config user.email "zuckung@gmx.de"
          git add .
          git diff-index --quiet HEAD || git commit -m "README.md updated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
